In [1]:
import numpy as np
import pandas as pd

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('whitegrid')
%matplotlib inline

In [3]:
rain = pd.read_csv('India_rainfall_act_dep_1901_2016_1.csv')

In [4]:
rain.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 116 entries, 0 to 115
Data columns (total 11 columns):
YEAR                              116 non-null int64
Actual Rainfall: JUN              116 non-null float64
Actual Rainfall: JUL              116 non-null float64
Actual Rainfall: AUG              116 non-null float64
Actual Rainfall: SEPT             116 non-null float64
Actual Rainfall: JUN-SEPT         116 non-null float64
Departure Percentage: JUN         116 non-null float64
Departure Percentage: JUL         116 non-null float64
Departure Percentage: AUG         116 non-null float64
Departure Percentage: SEP         116 non-null float64
Departure Percentage: JUN-SEPT    116 non-null float64
dtypes: float64(10), int64(1)
memory usage: 10.0 KB

In [5]:
rain.describe()

,YEAR,Actual Rainfall: JUN,Actual Rainfall: JUL,Actual Rainfall: AUG,Actual Rainfall: SEPT,Actual Rainfall: JUN-SEPT,Departure Percentage: JUN,Departure Percentage: JUL,Departure Percentage: AUG,Departure Percentage: SEP,Departure Percentage: JUN-SEPT
count,116.000000,116.000000,116.000000,116.000000,116.000000,116.000000,116.000000,116.000000,116.000000,116.000000,116.000000
mean,1958.500000,166.711207,294.135345,260.920690,173.710345,895.943966,-0.562931,-2.203448,0.375000,-1.219828,-0.976724
std,33.630343,36.133349,41.531085,37.237717,37.492936,92.796977,22.330344,14.009717,14.916037,22.628705,10.031701
min,1901.000000,85.700000,146.200000,189.800000,95.100000,697.400000,-48.300000,-54.200000,-32.500000,-44.700000,-24.900000
25%,1929.750000,141.425000,273.575000,237.000000,143.375000,828.175000,-15.525000,-8.550000,-9.925000,-19.525000,-8.300000
50%,1958.500000,167.250000,295.600000,259.800000,173.650000,904.050000,-2.200000,-2.000000,-0.500000,-1.850000,0.350000
75%,1987.250000,190.450000,322.400000,289.275000,201.925000,962.800000,13.675000,6.425000,12.625000,15.250000,5.300000
max,2016.000000,277.200000,381.600000,348.000000,283.100000,1124.200000,56.600000,26.600000,33.100000,64.500000,22.900000

In [6]:
rain.head(20)

,YEAR,Actual Rainfall: JUN,Actual Rainfall: JUL,Actual Rainfall: AUG,Actual Rainfall: SEPT,Actual Rainfall: JUN-SEPT,Departure Percentage: JUN,Departure Percentage: JUL,Departure Percentage: AUG,Departure Percentage: SEP,Departure Percentage: JUN-SEPT
0,1901,109.1,241.4,284.2,121.9,756.6,-29.9,-16.7,11.0,-28.4,-13.1
1,1902,104.0,283.7,202.6,201.9,792.1,-33.6,-2.0,-21.0,18.7,-9.1
2,1903,114.8,293.0,279.6,204.4,891.9,-26.6,1.6,9.6,20.3,2.6
3,1904,158.8,266.4,210.4,129.6,765.2,2.8,-7.7,-17.4,-23.8,-11.8
4,1905,88.7,252.5,202.6,174.6,718.5,-43.6,-12.3,-21.2,3.2,-17.4
5,1906,176.9,285.8,259.8,179.8,902.3,14.2,-1.1,2.1,6.4,4.0
6,1907,150.1,223.5,311.6,95.1,780.3,-3.3,-22.9,23.5,-44.7,-10.0
7,1908,125.4,331.5,317.0,153.8,927.7,-19.4,15.6,25.6,-9.5,7.4
8,1909,205.0,318.1,239.9,164.9,927.9,31.8,11.1,-6.0,-2.7,7.1
9,1910,208.0,248.1,296.9,187.2,940.2,33.5,-14.5,16.9,10.5,8.1
10,1911,189.5,158.5,212.5,183.1,743.5,21.7,-45.9,-16.4,7.9,-14.7
11,1912,104.9,337.6,267.7,119.6,829.8,-33.0,17.0,5.3,-29.9,-4.5
12,1913,214.4,272.0,189.8,108.0,784.3,38.0,-6.0,-25.6,-37.0,-10.0
13,1914,158.2,358.9,246.2,201.0,964.3,1.1,23.9,-4.3,17.6,10.4
14,1915,155.0,231.5,233.0,175.2,794.7,-1.3,-20.8,-9.3,2.4,-9.4
15,1916,233.8,301.5,318.8,202.0,1056.1,34.3,-5.7,20.6,14.9,13.2
16,1917,218.1,279.3,300.7,283.1,1124.2,37.8,-4.2,17.0,64.5,22.9
17,1918,206.3,180.4,240.7,109.1,736.5,13.5,-47.1,-11.4,-42.1,-24.9
18,1919,192.7,323.7,299.8,163.2,979.5,10.3,4.9,15.7,-11.4,5.9
19,1920,166.3,302.3,190.8,122.2,781.6,-5.6,0.6,-32.5,-33.3,-16.8